### PR TITLE
Trade Route edits

### PR DESCRIPTION
**Pull request by SimpleFish5655**
Setting up missing trade hubs with global variables.

### CODE REVIEW

**Comment by SimpleFish5655** [comment]
After further testing I couldn't find a way to keep the trade hub buildings in tribal holdings from getting destroyed when feudalizing, hence reverted the changes to spawn holdings in tribal counties

**Comment by Leviathonlx** [comment]
Hm I tested this and the building doesn't go away when feudalizing though the mod does put the trading post in the city of the county rather than the tribal holding which honestly makes more sense anyway.

**Comment by SimpleFish5655** [comment]
> Hm I tested this and the building doesn't go away when feudalizing 

That's odd. In my earlier commits I proposed a change which made the trade building spawn directly in the tribal holding which then got destroyed / converted when feudalizing. Did you test using the latest commit? May be why we saw different behaviour.

> though the mod does put the trading post in the city of the county rather than the tribal holding which honestly makes more sense anyway.

Disagree with this for a few reasons:
1. Mechanically: by putting it in the city holding, the player will not receive the majority of the tax income as it goes to the republican vassal
2. Historically:  it seems like the tribal holdings themselves should be the main trade centers. The way the mod implemented them, you would see the trade building not created in Ribe but in the city when Ribe was the actual trade hub.

**Comment by SimpleFish5655** [comment]
Whoops, I'm not sure why this pull request got closed when I was just trying to sync your changes with my fork

**Pull request closed without merging**
